/*
 version 3.5.160
*/
'use strict';var tnscm_adn;
(function(f,g,E){(function(){var C,F,L,I,O,M;C=function(){function q(){}function d(a,b){var e,h;if(a&&(h=a.length))for(e=0;e<h;e+=1)try{b(a[e],e,a)}catch(k){}}function c(a,b){for(var e=0,h=a.length;e<h;)if(a[e++]===b)return e-1;return-1}function r(a,b){return function(){return a.apply(b,arguments)}}function l(a,b,e){f.addEventListener?a.addEventListener(b,e,!1):f.attachEvent&&a.attachEvent("on"+b,e)}function n(a){function b(){d(n.f,function(a){a()});delete n.f}function e(){"loading"!==g.readyState&&
(b(),g.detachEvent("onreadystatechange",e))}"loading"!==g.readyState?a():n.f?n.f.push(a):(n.f=[a],g.addEventListener?g.addEventListener("DOMContentLoaded",b,!1):g.attachEvent&&g.attachEvent("onreadystatechange",e))}function s(a){function b(){for(s.time=w&&0<w.loadEventStart?new Date(w.loadEventStart):new Date;e.length;)e.shift()(s.time)}var e;s.time?a(s.time):(s.S||(s.S=[],l(f,"load",b)),e=s.S,e.push(a),"complete"===g.readyState&&b())}function y(a){var b={};a&&d(a.split("&"),function(a){a=a.split("=");
b[decodeURIComponent(a[0].toLowerCase())]=decodeURIComponent(a[1])});return b}function z(){var a=g.body,b=g.documentElement,a=a?Math.max(a.scrollHeight,a.offsetHeight,a.clientHeight):0;return Math.max(a,b.scrollHeight,b.offsetHeight,b.clientHeight)}function t(a,b){var e;return g.defaultView&&g.defaultView.getComputedStyle?(b=b.replace(/([A-Z])/g,"-$1").toLowerCase(),(e=g.defaultView.getComputedStyle(a,null))&&e.getPropertyValue(b)):a.currentStyle?a.currentStyle[b]:a.style&&a.style[b]?a.style[b]:null}
function B(a){if(!a)return{top:0,left:0};var b={top:a.offsetTop,left:a.offsetLeft};a=B(a.offsetParent);b.top+=a.top;b.left+=a.left;isNaN(b.top)&&(b.top=E);isNaN(b.left)&&(b.left=E);return b}function p(a){return a.contentDocument||a.contentWindow&&a.contentWindow.document||a.document||null}function x(a,b){for(var e=a.childNodes,h=e.length,k;h--;)if(k=x(e[h],b))return k;return b(a)}var A=["","moz","ms","webkit"],m=f.performance,w=m?m.timing:null,m=function(){if("undefined"==typeof navigator.plugins||
0==navigator.plugins.length)try{return!!new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(a){return!1}else return navigator.plugins["Shockwave Flash"]}();return{wa:q,random:function(){var a=(new Date).valueOf().toString();return parseInt(a.substr(a.length-8,a.length))+Math.round(Math.random()*Math.pow(10,9))},ha:m,trim:function(a){return String.prototype.trim!==E?String.prototype.trim.call(a):a.replace(/^\s+|\s+$/g,"")},a:d,indexOf:c,ua:function(a,b,e){var h,k;e=e||q;if(!a)return!1;k=a.length;
0===k&&e();return k?h=setInterval(function(){var c=10;do{k-=1;if(-1===k){clearInterval(h);e();break}b(a[k],k,a)}while(--c)},4):E},extend:function(a,b,e){var h,k;for(h in b)b.hasOwnProperty(h)&&(k=b[h],a[h]=e&&"function"===typeof k?r(k,a):k)},on:l,i:n,load:s,v:function(a){l(f,"scroll",a);l(f,"resize",a);a()},F:function(a,b){function e(){var e=g[k]||"visible";switch(e){case "hidden":b(e);break;default:a(e)}}var h,k;b=b||q;for(h=0;h<A.length;h++)if(k=A[h]+"VisibilityState",k=k.charAt(0).toLowerCase()+
k.substring(1),g[k]){l(g,A[h]+"visibilitychange",e);"hidden"!==g[k]&&e();return}e()},xa:y,ca:function(a){function b(a){var b=!1;d(["link1","clicktag","alink1","url","adress"],function(e){a.hasOwnProperty(e)&&(b=a[e])});return b}var e,h,k=a.childNodes,c=a.parentNode,m="",f={};switch(a.nodeName){case "IMG":for(;c;){if("A"===c.nodeName){e=c.href;break}c=c.parentNode}break;case "OBJECT":d(k,function(a){"PARAM"===a.nodeName&&"flashvars"===a.getAttribute("name").toLowerCase()&&(h=a.getAttribute("value"),
f=y(h.replace(/&amp;/g,"&")),e=b(f))});break;case "EMBED":if(m=a.getAttribute("flashvars"))f=y(m.replace(/&amp;/g,"&")),e=b(f)}try{"string"===typeof e&&(e=decodeURIComponent(e))}catch(g){}return e},ra:z,la:function(a){for(var b=!1,e=a.getClientRects(),h=z(),c=e.length;c--;)if(a=e[c],0!==a.width&&0!==a.height){if(0<a.top)return a.top<=h;if(0<a.bottom)return a.bottom<=h;b=!0}return b},sa:t,fa:B,K:function(a){var b={w:["paddingLeft","paddingRight","borderLeftWidth","borderRightWidth"],h:["paddingTop",
"paddingBottom","borderTopWidth","borderBottomWidth"]},e,h,c;"svg"==a.nodeName?(e=a.getBoundingClientRect(),e={w:Math.round(e.width),h:Math.round(e.height)}):e={w:a.offsetWidth,h:a.offsetHeight};for(h in e)if(e.hasOwnProperty(h)){if(0<e[h])for(c=b[h].length;c--;)e[h]-=parseInt(t(a,b[h][c]),10)||0;c=e[h]||t(a,"w"===h?"width":"height");/%/.test(c)||(e[h]=parseInt(c,10),isNaN(e[h])&&(e[h]=0))}return e},da:p,ga:function(){var a=g.body,b=g.documentElement;return"number"===typeof f.pageYOffset?f.pageYOffset:
b&&b.scrollTop?b.scrollTop:a&&a.scrollTop?a.scrollTop:0},$:x,ia:function(a){try{var b=a.getAttribute("src")||"",e=b.indexOf("//"+location.host),c;if((0!==b.indexOf("http")&&0!==b.indexOf("//")||-1<e&&8>e)&&(c=p(a))&&c.getElementById)return!0}catch(d){}return!1},J:function(a){function b(a){-1===c(excludeElements,a)&&excludeElements.push(a)}function e(a){var b=g.createElement("a");b.href=a;return b.href}var h,k,m;if(!a.tagName)return!1;if("OBJECT"===a.tagName){h=a.getAttribute("data");a=a.childNodes;
if(!h)for(k=a.length;k--;)if(m=a[k],"PARAM"===m.nodeName&&"movie"===m.getAttribute("name").toLowerCase())return m.getAttribute("value");for(k=a.length;k--;)if(m=a[k],"PARAM"===m.nodeName&&"flashvars"===m.getAttribute("name").toLowerCase()&&(m=y(m.getAttribute("value").replace(/&amp;/g,"&")),m.video1))try{return decodeURIComponent(m.video1)}catch(f){return m.video1}return h}if("VIDEO"===a.tagName){h=a.childNodes;m=h.length;var s,n;if(!a.canPlayType)return!1;for(k=0;k<m;k++)if(s=h[k],"SOURCE"===s.nodeName&&
(n=s.getAttribute("type"),a.canPlayType(n)))return h=s.getAttribute("src")||!1,d(a.getElementsByTagName("embed"),b),d(a.getElementsByTagName("object"),b),h;return h=a.getAttribute("src")}if("SVG"===a.tagName.toUpperCase())k=a.getElementsByTagName("image"),0<k.length&&(h=k[0].getAttribute("xlink:href"));else{k=(h=a.getAttribute("src"))&&"data:image"==h.substring(0,10);m=h&&(0==h.indexOf("//")||0==h.indexOf("http"));if(null==h||k)return h&&k?F.juke_host[0]||null:null;h=a.getAttribute("src");m||(h=e(h))}return h},
ea:function(a){var b={};if(top!=self&&f.addonCMeter&&f.addonCMeter&&addonCMeter.currentValues&&addonCMeter.currentValues.offset){var b=g.documentElement,e=g.getElementsByTagName("body")[0],b={w:f.innerWidth||b.clientWidth||e.clientWidth,h:f.innerHeight||b.clientHeight||e.clientHeight};return 10>=Math.abs(b.w-a.w)&&10>=Math.abs(b.h-a.h)?addonCMeter.currentValues.offset:0}return 0},r:function(){var a=F;return f.addonCMeter&&addonCMeter.config&&addonCMeter.config.region||a.region||"ua"}}}();F=function(g){var d=
{source:"source.mmi.bemobile.ua",juke_host:["pa.tns-ua.com/bug/pic.gif"],host:"pagestat.mmi.bemobile.ua",sslhost:"sslpagestat.mmi.bemobile.ua",err_host:"er.mmi.bemobile.ua",timer:{frequency:5,pings:[5,15,30,60,120],stop_after:5},ads:{scan_frequency:5,width:50,height:40},video:{url:"vplayer.mmi.bemobile.ua/vplayer/html5"}};g.extend(d,f.addonCMeter&&addonCMeter.config);d.custom_url&&location.host===d.custom_url.href?(d.ads.scan_frequency=d.custom_url.banner_scan_frequency,d.work_in_frame=d.custom_url.work_in_frame):
d.work_in_frame=!0;"string"===typeof d.juke_host&&(d.juke_host=[d.juke_host]);return d}(C);L=function(q,d){function c(a){var b;try{f.XDomainRequest?(b=new f.XDomainRequest,a&&(b.onerror=function(){a.call(null,b)})):(b=new XMLHttpRequest,a&&(b.onreadystatechange=function(){4==b.readyState&&200!=b.status&&a.call(null,b)}))}catch(e){console.error("cors:"+e)}return b}function r(a,b,e){var c="&";-1==a.indexOf("?")&&(c="?");return a+(c+b+"="+e)}function l(){for(var a=[],b=0;32>b;b++)a[b]="0123456789ABCDEF".substr(Math.floor(16*
Math.random()),1);a[12]="4";a[16]="0123456789ABCDEF".substr(a[16]&3|8,1);return a.join("")}function n(a,b,e){g.cookie=a+"="+escape(b)+(e?"; expires="+e:"")+"; path=/"}function s(a){var b=" "+g.cookie;a=" "+a+"=";var e=null,c=0,m=0;0<b.length&&(c=b.indexOf(a),-1!=c&&(c+=a.length,m=b.indexOf(";",c),-1==m&&(m=b.length),e=unescape(b.substring(c,m))));return e}function y(a){g.cookie=a+"=; expires=Thu, 01 Jan 1970 00:00:01 GMT;"}function z(){var a;try{a=g.getElementsByTagName("body")[0]}catch(b){}"undefined"!=
typeof a&&null!=a||"undefined"==typeof g.body||(a=g.body);return a}f.idCoreOnReady=function(a){w.onFlashReady(a)};f.tnsOnStatResult=function(a){console.log("result:"+a.result+" pid:"+a.ya+" e.id: "+a.id)};var t;try{t="localStorage"in f&&null!==f.localStorage}catch(B){t=!1}var p=function(){if("undefined"==typeof navigator.plugins||0==navigator.plugins.length)try{return!!new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(a){return!1}else return navigator.plugins["Shockwave Flash"]}(),x=/MSIE/.test(navigator.userAgent),
A=function(){var a=navigator.cookieEnabled?!0:!1;"undefined"!=typeof navigator.cookieEnabled||a||(g.cookie="testcookie",a=-1!=g.cookie.indexOf("testcookie")?!0:!1,y("testcookie"));return a}(),m=function(){var a="l";p?a="b":f.postMessage&&(t||A)?a="d":0==t&&0==A&&(a="g");try{if(f.chrome)for(var b in navigator.plugins)if(/PepperFlashPlayer/gi.test(navigator.plugins[b].filename)){a="c";break}}catch(e){console.warn("chrome : PepperFlashPlayer - has some error")}return a}(),w=function(){function a(){function a(){var b;
try{b=new CrossDomainStorage(N,"/cm/3.5.160/cm.html"),b.requestValue(u.id,function(a,b){w(b)})}catch(e){console.error("cds.js:"+e),v=l(),w(v)}}"undefined"===typeof CrossDomainStorage?d.j(G+"/cm/3.5.160/cds.js",a):a()}function b(){var a=new Date;a.setFullYear(a.getFullYear()+1);n(u.wasMigrated,!0,a.toUTCString());w(v)}function e(){return s(u.wasMigrated)?!1:A&&s(u.wasInitialized)?(v=s(u.id),t?(d.j(G+"/id-core/1.77-r59654/cds.js",function(){try{(new CrossDomainStorage(N,"/id-core/1.77-r59654/id.html")).requestValue(u.id+
":"+v,function(a,e){e!=v?console.error("id: "+e+" != "+v):b()})}catch(a){console.error("migrate:"+a)}}),y(u.id),y(u.wasInitialized)):p&&(f.tns_uid=v,d.j(G+"/id-core/1.77-r59654/flash.js",function(){b()})),!0):!1}function h(){R=!0;e()||(t?(v=localStorage.getItem(u.id))?w(v):f.postMessage&&!f.JSON&&f.localStorage?d.j(G+"/json2.min.js",function(){z()?a():d.ready(function(){a()})}):f.postMessage&&f.JSON&&f.localStorage?z()?a():d.ready(function(){a()}):w(l()):p?z()?d.j(G+"/id-core/1.77-r59654/flash.js"):
d.ready(function(){d.j(G+"/id-core/1.77-r59654/flash.js")}):((v=s(u.id))||(v=l()),w(v)))}function k(){for(var a in D)if(D.hasOwnProperty(a)){var b=D[a].url,e=D[a].params,c=D[a].time,m=D[a].type,d=D[a].onError;/^POST$/gi.test(m)?Q(b,e,c,d):B(b,e,c,m,d)}D=[];for(var h in H)H.hasOwnProperty(h)&&H[h].call(this,v);H=[]}function w(a){var b=K.length;v=a;if(t)localStorage.setItem(u.id,a);else if(A){var e=new Date;e.setFullYear(e.getFullYear()+1);n(u.id,a,e.toGMTString());n(u.wasInitialized,!0,e.toGMTString())}J=
!0;k();if(t){if(!localStorage.getItem(u.flag)){for(;b--;)(new Image).src=location.protocol+"//"+K[b]+"?uid="+a+"&time="+(new Date).valueOf();localStorage.setItem(u.flag,"true")}}else if(A&&!s(u.flag)){e=new Date;e.setFullYear(e.getFullYear()+1);for(n(u.flag,"true",e.toGMTString());b--;)(new Image).src=location.protocol+"//"+K[i]+"?uid="+a+"&time="+(new Date).valueOf();localStorage.setItem(u.flag,"true")}}function P(a,b){var e,c;if(b instanceof Array)for(e in b)a=r(a,b[e].key,b[e].value);else for(c in b)a=
r(a,c,b[c]);return a}function Q(a,b,e,m){try{var d=c(m);d.open("POST",a,!0);b||(b={});b instanceof Array?(b.push({key:"cookie",value:v}),b.push({key:"time",value:e?e:(new Date).valueOf()})):(b.cookie=v,b.time=e?e:(new Date).valueOf());x?d.contentType="text/plain":d.setRequestHeader("Content-type","application/x-www-form-urlencoded;charset=UTF-8");var h=P("?",b).replace(/^\?/,"");d.send(h)}catch(k){console.error(k)}}function B(a,b,e,m,d){b||(b={});a=r(a,"cookie",v);a=r(a,"time",e?e:(new Date).valueOf());
a=P(a,b);try{if(m&&"JSONP"==m||f.opera&&!("withCredentials"in new XMLHttpRequest)){var h=g.createElement("script");h.setAttribute("src",a);g.getElementsByTagName("head")[0].appendChild(h)}else{var k=c(d);k.open("GET",a,!0);0==x&&k.setRequestHeader("Accept","application/json");k.send()}}catch(s){console.log(s)}}var J=!1,N=location.protocol+"//"+(q.source||"source.mmi.bemobile.ua"),G=f.addonCMeter&&addonCMeter.hostAddon||N,S="1.77-r59654".replace(/-r\d+$/,""),K=["pa.tns-ua.com/bug/pic.gif","juke.mmi.bemobile.ua/bug/pic.gif"];
try{q&&q.juke_host&&(K=q.juke_host)}catch(C){console.warn(C)}var u={id:"vplayer_user_id",wasInitialized:"tns_was_initialized",wasMigrated:"tns_was_migrated",flag:"flag"},R=!1,D=[],v="",H=[];return{init:function(){0==R?A&&!s(u.wasMigrated)?z()?h():d.ready(function(){h()}):h():J&&k()},send:function(a,b,e,c){b||(b={});b.vt=m;var d=(new Date).valueOf();J?/^POST$/gi.test(e)?Q(a,b,d,c):B(a,b,d,e,c):D.push({url:a,params:b,type:e,time:d,onError:c})},onFlashReady:function(a){try{var b=g.getElementById("div_holder");
b.parentNode.removeChild(b)}catch(e){}swfobjectlite=null;w(a)},addOnReadyListener:function(a){H.push(a)},isReady:function(){return J},getId:function(){return v},version:function(){return S}}}();f.IDCore=f.IDCore||w;w.init();return w}(F,function(f){var d={j:function(c,d){function l(c){n.onload=n.onerror=n.onreadystatechange=null;d&&"function"==typeof d&&d(c)}var n=g.createElement("script"),s=g.head||g.getElementsByTagName("head")[0];f.extend(n,{async:!0,type:"text/javascript",onload:function(){l(null)},
onerror:l,onreadystatechange:function(){"loaded"!==n.readyState&&"complete"!==n.readyState||l(null)}});n.src=c;s.insertBefore(n,s.lastChild)},i:function(c){function f(){each(d.i.f,function(c){c()});delete d.i.f}function l(){"loading"!==g.readyState&&(f(),g.detachEvent("onreadystatechange",l))}"loading"!==g.readyState?c():d.i.f?d.i.f.push(c):(d.i.f=[c],g.addEventListener?g.addEventListener("DOMContentLoaded",f,!1):g.attachEvent&&g.attachEvent("onreadystatechange",l))},ready:function(c){d.i(c)}};return d}(C));
I=function(g){function d(d,f){c[d]||(c[d]=[]);c[d].push(f)}var c={};return{za:c,c:function(r,l){f.cm_events&&f.cm_events.join?g.a(f.cm_events,function(c,g){c&&c.event==r&&(d(r,c.callback),delete f.cm_events[g])}):f.cm_events=[];g.a(c[r],function(c){l=c.call(this,l)});return l},on:d}}(C);O=function(q,d,c,r){function l(g,l){var n=this,t=top!==self;d.on(f,"beforeunload",function(){n.qa=!0});2<=arguments.length&&d.extend(this,l,!0);this.b=this.b||[];this.b[0]="~cm_"+g+"~";setTimeout(function(){function l(p){"AddonCMeterReady"===
p.data&&(f.removeEventListener("message",l,!1),d.extend(r,f.addonCMeter&&addonCMeter.config),M.oa(c.c("templates:yes",[]),c.c("templates:no",[])),n.t(c.c("init_"+g)))}var p=t?"AddonCMeterFrame":"AddonCMeterMain";f.localStorage&&"initializing"===localStorage.getItem(p)||f.sessionStorage&&"initializing"===sessionStorage.getItem(p)||f.sessionStorage&&"initializing"===sessionStorage.getItem("AddonCMeter")?f.addEventListener("message",l,!1):n.t(c.c("init_"+g))},20)}var n="3.5.160_"+d.r()+"/"+q.version();
d.extend(l.prototype,{D:"GET",origin:location.protocol+"//"+("https:"===location.protocol?r.sslhost:r.host),pa:d.random(),V:function(){return f.addonCMeter&&addonCMeter.currentValues&&addonCMeter.currentValues.sid||this.pa},ba:function(){var c={location:encodeURIComponent(f.location.href),referrer:encodeURIComponent(this.referrer||g.referrer),is_flash:d.ha?"1":"0",session_id:this.V(),version:n,sw:screen.width,sh:screen.height,scd:screen.colorDepth};screen.pixelDepth&&(c.spd=screen.pixelDepth);f.addonCMeter&&
addonCMeter.PLID&&(c.tnscm_plid=addonCMeter.PLID);f.tnscm_cat&&(c.tnscm_cat=tnscm_cat);tnscm_adn&&(c.tnscm_adn=tnscm_adn);f.tnscm_pak&&(c.tnscm_pak=tnscm_pak);return c},send:function(){this.P?this.P():this.p()},p:function(){var f=0,g,l={},n=[];d.extend(l,this.ba());for(d.extend(n,this.b);n.length;)if(f+=1,(g=n.shift())||0===g)l["param"+f]=g;d.extend(l,n);q.send(this.url,c.c("send",l),this.D)}});d.extend(l.prototype,{url:l.prototype.origin+"/pagestat/PageStatEntry"});return l}(L,C,I,F);M=function(q,
d){function c(c){var d=this,f=["w","h"],g=["src"];this.h=this.w=null;q.a(c,function(c){var l,q=parseInt(c,10);if(!isNaN(q))l=f.shift();else if(c instanceof RegExp||"RegExp"==c.constructor.name)l=g.shift(),q=c;l&&(d[l]=q)});this.src||!this.w&&!this.h||(this.src=/./)}var r={};q.extend(c,{o:function(d){var g=!0,s=!1,r={Z:[],current:[]};q.a(d,function(d){d instanceof RegExp||"RegExp"==d.constructor.name?g=s=d.test(f.location.host):g&&!s?r.Z.push(new c(d)):g&&s&&r.current.push(new c(d))});return r},embeds:function(c){var d=
[],f=[],r=[];c=c||g;q.a(c.getElementsByTagName("embed"),function(c){for(var g=c.parentNode;g;){if("OBJECT"===g.nodeName){f.push(g);break}g=g.parentNode}-1===q.indexOf(r,c)&&d.push(c)});q.a(c.getElementsByTagName("object"),function(c){-1===q.indexOf(f,c)&&-1===q.indexOf(r,c)&&d.push(c)});return d},g:function(c){function d(c,f){q.a(r.B[c],function(c){c.check(f[0],f[1],f[2])&&(g=!0)});g&&q.a(r.N[c],function(c){c.check(f[0],f[1],f[2])&&(g=!1)})}var f=[],g,z;q.a(c,function(c,l){g=!1;for(z in r.B)r.B.hasOwnProperty(z)&&
d(z,c);g&&f.push(l)});return f}});q.extend(c.prototype,{check:function(c,d,f){return this.src&&!this.src.test(c)||this.w&&this.w!==d||this.h&&this.h!==f?!1:!0}});setTimeout(function(){r.B=c.o(d.c("templates:yes",[[/betsonsport\.ru\/img\//i],[/\.2mdn\.net\//i],[/googlesyndication\.com\/sadbundle\//i,970,90],[/\/\/meta\.ua\/img\/b4\//i],[/5\.10\.35\.208\//i],[/\.gvt1\.com\//i],[/widget\.mediastealer\.com\/dating\//i],[/adpartner\.pro\//i],[/commersant\.ge\/uploads\//i],[/palitra\.ge\/baner\//i],[/\/html5\//i],
[/picz\.ge\//i],[/banner\.volynnews\.com/i],[/\.googlesyndication\.com\/simgad\//i],[/weborama\./i],[/ads\.locals\.md\//i],[/numbers\.md/i],[/\.zingan\.com\//i],[/cdn\.epom\.com\//i],[/\.vcdn\.biz\//i],[/sourcefabric\.net\//i],[/media\.adrcdn\.com\/ads\//i],[/base\.kiwi\.kz\//i],[/\.rontar\.com\//i],[/static\..*\.kcdn\.kz\//i],[/\.adocean\.pl\//i],[/dotua\.org\//i],[/advideo\.com\.ua\//i],[/admixer\.net/i],[234,200],[205,333],[205,280],[205,60],[950,90],[760,90],[730,60],[730,90],[728,90],[640,90],
[500,100],[468,120],[468,60],[320,60],[300,600],[300,250],[300,240],[285,130],[250,250],[240,400],[240,350],[240,200],[240,90],[230,90],[230,60],[180,150],[160,600],[160,60],[150,60],[120,600],[120,240],[120,60],[/adriver\.ru/i],[/bannerka\.ua/i],[/adfox\.ru\//i],[/reclama\./i],[/c8\.net\.ua\//i],[/bbn\.img\.com\.ua/i],[/images\.rambler\.ru\/upl\//i],[/baner\./i],[/ad.*\.bigmir\.net/i],[/\/banners_files\/.*\./i],[/b\.ex\.ua\/.*\/.*\.swf/i],[/\/openx\/www\/images\/.*\./i],[/\/bnr\//i],[/\/adban\/.*\/.*\/.*\./i],
[/informers\.sinoptik\.ua/i],[/adnet\.com\.ua\/banners\/.*\/.*\/.*\/.*\./i],[/rose\.ixbt\.com/i],[/\/adv\//i],[/i\.holder\.com\.ua\/.*\/.*\/.*\/.*\./i],[/\/images\/.*\/.*\/.*\/.*\.swf$/i],/mkurnali\.ge/,[/openx\.palitra\.ge\/baner\/nesquik_mkurn/i],/kids\.ge/,[/images\/ads\/20170906_nesquik/i],/biz\.nv\.ua/,[970,90],/5\.ua/,[970,90],/vidal\.ge/,[/\/assets\/uploads\/31\//i],[/assets\/ads\/prospan\//i],[/\/assets\/uploads\/6b\//i],[/\/assets\/uploads\/26\//i],[/\/assets\/uploads\/41\//i],[/\/assets\/uploads\/4f\//i],
/marketer\.ge/,[/img\.marketer\.ge\/2017\/05\//i],/5\.10\.35\.208\//,[260,410],/myvideo\.ge/,[/open2\.myvideo\.ge\/video\/suratebi\//i],[/metric\.ge\/banner\//i],[/open5\.myvideo\.ge\/delivery\//i],/ambebi\.ge/,[/openx\.ambebi\.ge\/www\/images\//i],[300,900],[1010,112],[/openx\.ambebi\.ge\/www\/images\//i],[600,90],/amindi\.ge/,[/bms\.adjarabet\.com\//i],[260,410],[/amindi\.ge\/images\/banners\//i],[/banners\.amindi\.ge\//i],/tengrinews\.kz/,[240,227],[240,400],/olx\.kz/,[617,90],[240,400],[160,584],
/krisha\.kz/,[250,220],[240,400],[960,100],/kolesa\.kz/,[240,400],[468,60],[960,100],/kapital\.kz/,[300,200],/nur\.kz/,[248,283],[250,256],[/\/advert\//i],/look\.tm/,[683,100],[300,300],[258,258],/net\.adjara\.com/,[/staticnet\.adjara\.com\/images\//i],/imovies\.cc/,[/62\.212\.33\.85\/movie_files1\//i],/newposts\.ge/,[/\/banner/i],/kulinaria\.ge/,[300,300],[200,230],[620,90],/liberali\.ge/,[780,100],[390,100],/commersant\.ge/,[135,212],[220,110],[714,100],[275,130],[270,100],[272,105],[272,90],[270,
107],/myauto\.ge/,[/static\.my\.ge\/myauto\/banners\//i],/\.ge/,[/\.ge\/www\/delivery\/afr\.php/i],[/\/www\/images\//i],[/baner/i],[640,100],/adjaranet\.com/,[/banner/i],/horoskopi\.ge/,[300,300],/wom\.ge/,[300,100],/\.kz/,[728,200],[/\/banners/i],/allfun\.md/,[295,295],[476,102],/alltravel\.md/,[168,138],[215,155],[210,138],[394,88],/odessa-life\.od\.ua/,[/\/banners\//i],/volynnews\.com/,[460,145],[220,180],/moldova\.org/,[301,301],/tsamali\.ge/,[580,100],/forum\.ge/,[240,50],/i.*p.*n.*\.ge/,[/\/www\/images\/.*\./i],
/file\.ge/,[/\/ad.*\./i],/\.md/,[/\/banner/i],/mail\.ru/,[/r\.mradx\.net\//i,300,300],[/r.*\.mail\.ru\/b.*\.gif$/i],[/r.*\.mail\.ru\/b.*\.png$/i],[/r.*\.mail\.ru\/b.*\.jpg$/i],[/r.*\.mail\.ru\/b.*\.swf$/i],[/promoblocks\.ru/i],/football\.ua/,[/spadsmedia\.com\/www\/delivery\/afr\.php\//i],[/sportingbet\.host\.bannerflow\.com\//i],/total\.kz/,[1E3,115],[/\/gb\.php..*=/i],/namba\.net/,[468,90],[1E3,90],[200,350],/magnolia-tv\.com/,[668,60],[300,100],[/\/files\/ban\//i],[100,100],/companion\.ua\//,[960,
90],/172\.16\.0\./,[/\.gif/i],[/\.png/i],[/\.swf/i],[/\.jpeg/i],[/\.jpg/i],/besplatka\.ua/,[660,90],[300,300],/ex\.ua/,[/ad_click/i],/aviso\.ua/,[/banner\.ool\.ua\//i]]))},4);setTimeout(function(){r.N=c.o(d.c("templates:no",[[/cackle\.me\//i],[/cdn\.spongecell\.com\//i],[/254a\.com\//i],[/cdn\.nudetubesex\.com\//i],[/adx\.bibl\.uk\//i],[/\.me\//i],[/\.ru\/.*n=ololo/i],[/tdsrmbl\.net\//i],[/uw3zcf6hoitob\.ru\//i],[/am15\.net/i],[/delivery-dev\.promo\.ge\//i],[/cdn\.mv\.myvideo\.ge\//i],[/eas3\.emediate\.se\//i],
[/xcetkbl\.com\//i],[/inv-nets\.admixer\.net\/.*\.aspx/i],[/ssp-rtb-asrv214\.sape\.ru\//i],[/^https:\/\/pa\.tns-ua\.com\//i],[/menswatchcentral\.com\//i],[/suenosouvenir\.com\//i],[/clicksor\.net\//i],[/brightonclick\.com\//i],[/rtbfy\.com\//i],[/myvideo\.ge\/secure\//i],[/admedia\.com\//i],[/bbrother\.org\//i],[/navaxudoru\.com\//i],[/hostingstrong\.com\//i],[/udsp-.*\.exe\.bid\//i],[/ismatlab\.com\//i],[/undefined$/i],[/ssp-rtb\.sape\.ru\//i],[/hobbiya\.com\.ua\/.*\.jpg$/i],[/viyar\.ua\/upload\//i],
[/terraclicks\.com\//i],[/tabletki\.ua\//i],[/\/images\/products\//i],[/serving\.plexop\.net\//i],[/loikfuriss\.info\//i],[/data\.whicdn\.com\/images\//i],[/pubonet\.fr\/show_i\.php/i],[/http:\/pagead\/ads/i],[/sofino\.ua\/img\//i],[/capital\.ua\/uploads\//i],[/ubercpm\.com\//i],[/tq\.abcdn\.bid\//i],[/adventori\.com\//i],[/installball\.com\//i],[/interesty\.net\//i],[/tengrinews\.kz\//i],[/ultra\.trophymanager\.com\//i],[/advinapps\.com\/ads/i],[/beelure\.com\//i],[/tmstorage\.com\//i],[/creativnost\.com\.ua\//i],
[/tredman\.com\//i],[/\.adk2x\.com\//i],[/kinopoisk\.ru\/film\//i],[/lyk9soryi3\.ru\//i],[/sld-ad\.ictv\.ua\//i],[/\.bigmir\.net\/attach\//i],[/laguna\.ua\/production\//i],[/shoessale\.com\.ua\/.*\/thumb/i],[/reports\.sld\.kiev\.ua\//i],[/golosno\.com\.ua\/sites\/default\/files\/\/styles\//i],[/appwall-performance\.com\//i],[/government\.in\.ua\/code\.html/i],[/rfadver\.com\//i],[/^blob:/i],[/dumskaya\.net\/pics\//i],[/rapidlinks\.org\//i],[/cheerless\.ru\//i],[/\.admixer\.net\/test1\/.*\/\..\[phId=/i],
[/\.vcdn\.biz\/.*\/type\.amlst\//i],[/orangeapps\.ru\//i],[/news\.abomus\.com.*\/sites\/default\/files\//i],[/\.solvemedia\.com\//i],[/att.*\.i\.ua\/attach\//i],[/fr\.ybx\.io\/creative\//i],[/m6bgdvvgi8\.ru\//i],[/technologiestuart\.com\//i],[/\.vcdn\.biz\/.*\.ts$/i],[/qaylie\.ru\//i],[/technologiesaintjoseph\.com\//i],[/\.dotua\.org\/fgh\.js/i],[/ctnsnet\.com\//i],[/myvideo\.ge\/movies\//i],[/site-analytics\.info\//i],[/algovid\.com\//i],[/agitated\.ru\//i],[/quentina\.ru\//i],[/servplay\.net\//i],
[/orion-site\.com\/ajax/i],[/\.admixer\.net\/test1\/.*\/\..someClick=/i],[/mwayss\.com\/ads/i],[/laredoute\.com\/products\//i],[/newstok\.ru\//i],[/anarrma\.ru\//i],[/avalln\.ru\//i],[/ecpmrocks\.com\//i],[/ainulindal\.ru\//i],[/anghabar\.ru\//i],[/e-protected\.ru\//i],[/a\.c8\.net\.ua\/.*frame\.php/i],[/ad5ve\.com\//i],[/socauth\.privatbank\.ua\//i],[/atemda\.com\//i],[/atmsrv\.com\//i],[/meta\.vcdn\.biz\/.*_megogo/i],[/dotua\.org\/player\.js/i],[/cdn\.vm-corporate\.com\//i],[/xl415\.com\//i],[/ad-maven\.com\//i],
[/vindicosuite\.com\//i],[/telephone-store\.ru\//i],[/rev2pub\..*com\//i],[/admtpmp.*\.com\//i],[/media\.adk2x\.com\//i],[/wheelpath\.com\//i],[/tools\.freehost\.com\.ua\//i],[/login\.snw\.media\//i],[/gocash01\.net\//i],[/tmdn.*\.com\//i],[/clike\.su\//i],[/mtagmonetizationb\.com\//i],[/rafomedia\.com\//i],[/9f6qmf0hs\.ru\//i],[/cpmaffiliation\.com\//i],[/regiepublicitairecpm\.com\//i],[/cpmad.*\.com\//i],[/admediacpm\.com\//i],[/prd.*\.rontar\.com\/productiframe\.axd/i],[/ato\.mx\//i],[/trafficmonsoon\.com\//i],
[/\.com\/t\.php.*a=96/i],[/rvfrm2010\.com\//i],[/touch1\.ru\//i],[/dataffastguru\.info\//i],[/playitviral\.com\//i],[/avenue\.center\//i],[/imgsrv\.io\//i],[/srv-statistics\.com\//i],[/cptlsrv\.com\//i],[/adsrvmedia\.net\//i],[/atdmt\.com\//i],[/memeglobal\.com\//i],[/wntg2x\.com\//i],[162,228],[/w55c\.net\//i],[/pipesarcade\.com\//i],[/groovitdigital\.com\//i],[/coolad9\.com\//i],[/blkz2x\.com\//i],[/servd2wn\.com\//i],[/yieldmedia\.net\//i],[/adv679854\.ru\//i],[/semantichelper\.com\//i],[/connect\.ok\.ru\//i],
[/bidvertiser\.com\//i],[/lightquartrate\.com\//i],[/8838d3aa4a6\.com\//i],[/r3\.c8\.net\.ua\/match_dsp\.php/i],[/delivery\.promo\.ge\//i],[/connexity\.net\//i],[/ad131m\.com\//i],[/merchenta\.com\//i],[/yu0123456\.com\//i],[/cured\.com\//i],[/wtp101\.com\//i],[/trk-xzz\.com\//i],[/de17a\.com\//i],[/getsecureweb\.com\//i],[/tesel8\.com\//i],[/everesttech\.net\//i],[/imrk\.net\//i],[/h\.holder\.com\.ua\/f/i],[/starkcom\.net\/srv/i],[/r.*\.c8\.net\.ua\/getiframe\.php/i],[/localpages\.com\//i],[/leisure\.com\//i],
[/teracreative\.com\//i],[/rernd\.com\//i],[/revsci\.net\//i],[/secure\..*trk.*\.com\//i],[/rtbidder\.net\//i],[/mediasoul\.net\//i],[/inb\.genorithm\.com\//i],[/goo\.mx\//i],[330,220],[/kapcha/i],[/img\/article\//i],[/design\.vesti-ukr\.com\//i],[/^http:\/\/undefined/i],[/linkis\.com\//i],[/magnetix\..*\//i],[/ipvertising\.com\//i],[/shop_image/i],[/sfera-tv\.com\.ua\/.*img\//i],[/ukrinform\.ua\/cgi-bin\//i],[/unian\..*\/cgi-bin\//i],[/iqalhcxcqz\.ru\//i],[/ritorno\.ru\//i],[/kleopatra0707\.com\//i],
[/107\.23\..*\..*\//i],[/img\.com\//i],[/otzovik\.com\/product\//i],[/ftop\.ru\//i],[/osvita\.ua\/.*image/i],[/fotos\..*\/images\//i],[/adroll\.com\//i],[/showbiza\.com\/.*photo/i],[/utro\.ua\/static\/adsense\//i],[/ikea\.com\//i],[/easyhits4u\.com\//i],[/img\.4mama\.com\.ua\//i],[/websteroidsapp\.com\//i],[/\.websearch\./i],[/searchsupporter\.info\//i],[/infoseekerapp/i],[/lookforithere\.info\//i],[/click2dad\.net\//i],[/pheasantissueflummery/i],[/bidswitch\.net\//i],[/targetix\.net\//i],[/people-group\.su\//i],
[/mynagor\.com\//i],[/fsua_items\/screen\//i],[/orbit\.lun\.ua\//i],[/google\.com/i],[/hotline\.ua\/price\//i],[/\.googleapis\.com\//i],[/nxnxcaqicm/i],[/apis\.google\.com\//i],[/adone\.ru\//i],[/advertbox\.us\//i],[/quikdisplay\.com\//i],[/thespatialists\.com\//i],[/adimps-perf\.com\//i],[/tooljava\.org\//i],[/gettvwizard\.com\//i],[/mybb\.ru\//i],[/lollipop-network\.com\//i],[/playblasteroids\.com\//i],[/dumedia\.ru\//i],[/hoptopboy\.com\//i],[/kvihit\.com\//i],[/imagevenue\.com\//i],[/obrona\.org\//i],
[/null$/i],[/interakt\.md\/content/i],[/gwallet\.com\//i],[/predictormedia\.com\//i],[/dotomi\.com\//i],[/mobileadhost\.com\//i],[/adsoptimizer\.net\//i],[/ad-sys\.com\//i],[/drivesection\.net\//i],[/tooldiv\.net\//i],[/livexjs\.net\//i],[/fellabooks\.net.*\/$/i],[/chocolatemx\.net\//i],[/aspire-guitar\.com\//i],[/golinkon\.info\//i],[/perfectnavigator\.com\//i],[/aceadsys\.net\//i],[/\.googlesyndication\.com\/pagead\//i],[/tracking\.m6r\.eu\//i],[/zedo\.com\//i],[/gogorithm\.com\//i],[/pdmayt\.com\//i],
[/metrigo\.com\//i],[/vdaqyqwsrd\.ru\//i],[/qrdeom\.com\//i],[/tatami-solutions\.com\//i],[/cloudfront\.net\//i],[/mrlmedia\.net\//i],[/mothernist\.hiro\.tv\//i],[/\.wlboon\.com\//i],[/admetaserver\.com\//i],[/tags\.qservz\.com\//i],[/neomion\.com\//i],[/^http:\/\/54\./i],[/x\.abk954\.com/i],[/creative\.xtendmedia\.com\//i],[/statisticsreporting\.com\//i],[/imhonet\.ru\/element\//i],[/mailsmania\.ru\//i],[/\.ru\/show_banner\//i],[/romilit\.com\//i],[/proligtb\.com\//i],[/brucelead\.com\//i],[/exebid\.ru\//i],
[/koluty\.com\//i],[/\.retark\.com\//i],[/com\.adv\.vz\.ru\//i],[/webmoney\.ua\/tools\//i],[/weropiy\.com\//i],[/\/games\/img\//i],[/maikaru\.ru\/picture\//i],[/zvek\.com\.ua\/images\//i],[/get_qrapi/i],[/grandcapital\.ru\/static\/img/i],[/img\.ubr\.ua\/banners\/.*adsense\./i],[/ticket\.net\//i],[/creativecdn\.com\//i],[/greefl\.com\//i],[/\.jutulep\.com\//i],[/baseflash\.com\//i],[/media\.tumblr\.com\//i],[/static\.com\//i],[/ssp\.adriver\.ru\/cgi-bin\/sync\.cgi/i],[/tractionize\.com\//i],[/secure\.demand-go\.com\//i],
[/rbc\.ua\/static\//i],[/yourbucks\.org\//i],[/datamind\.ru\//i],[/fresh-cup\.org\//i],[/ad\.starlightmedia\.ua\//i],[/financecontext\.ru\//i],[/attiveri\.com\/.* $/i],[/youtube\.com\//i],[/meta\.ua\/cell\.php/i],[/paramedjo\.com\//i],[/intencysrv\.com\//i],[/kilopog\.com\//i],[/gravyseals\.com\//i],[/media6degrees\.com\//i],[/lokomusic\.com\//i],[/tisa.ama\.com\/banner\.php/i],[/ministerial5\.com\//i],[/admailtiser\.com\//i],[/adgorithms\.com\//i],[/\/media\/gallery\//i],[/\.dotua\.org\/.*\/cover\/.*\.jpg$/i],
[/wp-content\/upload/i],[/netdna-cdn\.com\//i],[/\/logo/i],[/adsmile\.biz\//i],[/medads\.ru\//i],[/gittigidiyor\.com\//i],[/oneund\.com\//i],[/xmasdom\.com\//i],[/rainoftraffic\.info\//i],[/1xbet\.com\//i],[/clkrev\.com\//i],[/pub-fit\.com\//i],[/clicksor\.com\//i],[/sendspace\.com\//i],[/pgssl\.com\//i],[/rutarget\.ru\//i],[/datropy\.com\//i],[/dolka\.ru\//i],[/batanga\.net\//i],[/adorika\.net\//i],[/rfihub\.com\//i],[/loponop\.com\//i],[/palgames\.info\//i],[/play882\.info\//i],[/medialand\.ru\//i],
[/flashgames.*\..*\//i],[/funnygamezer\.info\//i],[/cloudgamezer\.com\//i],[/games\.info\//i],[/utrehter\.com\//i],[/intag\.co\/.* $/i],[/adk2\.com\//i],[/img\.admaster\.net\//i],[/openx\.net\//i],[/firstadvplug\.com\//i],[/pirrit\.com\//i],[/metka\.ru\//i],[/tomobol\.com\//i],[/adzoook\.com\//i],[/adservingfree\.info\//i],[/drgo\.ru\//i],[/slopty\.ru\//i],[/tradedoubler\.com\//i],[/fastloca\.com\//i],[/hide4you\.com\//i],[/proxy\.net\//i],[/bannerhost\.ru\//i],[/bannercity\.ru\//i],[/m2pub\.com\//i],
[/theseaapp\.com\//i],[/holisticmedicalwellness\.com\//i],[/qonenoj\.ru\//i],[/amazonaws\.com\//i],[/ipicture\.ru\/uploads\//i],[/reacten\.com\//i],[/ad\.mail\.ru\/adi\//i],[/k8media\.com\//i],[/notificatoin\.com\//i],[/co-co-co\.co\//i],[/\.dd34\.ru\//i],[/screenshot/i],[/yidop\.com\//i],[/pokitom\.com\//i],[/perfectmoney\.is\//i],[/20dollars2surf\.com\//i],[/bet-at-home\.com\//i],[/\.derploime\.com\//i],[/\.nekki\.ru\/banner\.php/i],[/tlvmedia\.com\//i],[/yoz5\.info\//i],[/game.*\.info\//i],[/exchange\.com\//i],
[/media-servers\.net\//i],[/gnezdo\.ru\//i],[/quelliclub\.ru\/slider\//i],[/all\.biz\/img\/.*\/catalog\/.*\./i],[/azd3\.info\//i],[/26sec\.com\//i],[/magicplayer\.torrentstream\.org\//i],[/refban\.com\//i],[/microads\.ru\//i],[/scanmedios\.com\//i],[/trkclk\.net\//i],[/game.*\.com\//i],[/porn\..*com\//i],[/\.ua\/delivery\/afr\.php/i],[/ro2\.biz\/ad\.php/i],[/gmodules\.com\//i],[/bremdy\.ru\//i],[/biglu\.ru\//i],[/pricora\.com\//i],[/twitbridge\.com\//i],[/resultsaccelerator\.net\//i],[/gayua\.com\//i],
[/okitspace\.com\//i],[/yottos\.com\//i],[/teaserjs\.info\//i],[/wambacdn\.net\//i],[/adultadworld\.com\//i],[/adnetworkme\.com\//i],[/seethisinaction\.com\//i],[/cameleo\.ru\//i],[/exoclick\.com\//i],[/\.rubiconproject\.com\//i],[/\.adnetwork.*\.net\//i],[/mediads\.info\//i],[/\.zanox\.com\//i],[/\.abnad\.net/i],[/reachjunction\.com\//i],[/\.e-viral\.com\//i],[/\.traffichaus\.com\//i],[/\.cmle\.ru\//i],[/datam\.com\//i],[/improvemedianetwork\.com\//i],[/adxplosions\.com\//i],[/mediaplex\.com\//i],
[/redintelligence\.net\/request_content\.php/i],[/baserve\.net\/serve\.php/i],[/ktbt\.ru\/b\.php/i],[/sociomantic\.com\//i],[/yangot\.com\//i],[/static.*\.rutracker\.org\/iframe/i],[/partners\.otpusk\.com\/media\.php/i],[/image\.tsn\.ua\/media\/images/i],[/nepalon\.com\//i],[/\.56.*\.net\/.*2\.php/i],[/\/vast\.php/i],[/ad.*\.adkserve\.com\//i],[/s\.holder\.com\.ua\/s/i],[/\.avazu\.net\//i],[/media\.glispa\.com\//i],[/squirrelsigdrs\.in\//i],[/overridingnichts\.in\//i],[/tecontx\.com\//i],[/ad-srvr\.com\//i],
[/pswec\.com\//i],[/hubrus\.com\//i],[/beatwaretranscribing\.in\//i],[/ads\.people-group\.net/i],[/holyclick\.ru/i],[/\.bidsystem\.com/i],[/zpk200\.com\/serve/i],[/imgads\..*\.net\/afr\.php/i],[/\.btricl3\.ru\/js\/rot\.php/i],[/\.tizerbank\.com\//i],[/\.plomihy\.com/i],[/static\.adv.*\.ru\/banners\//i],[/meta\.ua\/f_new\.asp/i],[/bdv\.bidvertiser\.com\/bidvertiser\.dbm/i],[/squirrelsigdrs\.in\/banners\/show\.php/i],[/code\.gif/i],[/calend\.ru\/img\/calendar\//i],[/hochu\.ua\/images\/articles\//i],
[/tagcloud\.swf/i],[/\.host\.bannerflow\.com\//i],[/myinfotopia\.com\//i],[/swfhttprequest\.swf/i],[/cityads\.ru\//i],[/\/www\/delivery\//i],[/z5x\.net\//i],[/adotube\.com\//i],[/lux-bn\.com\.ua\//i],[/criteo\.com\//i],[/autocompleteplus\.com\//i],[/akamai.*\.net\//i],[/etgdta\.com/i],[/soundmanager.*\.swf/i],[/player\.swf/i],[/img\.traffim\.com\//i],[/sharedaddomain\.com\//i],[/avalala\.com\//i],[/meta\.ua\/img\/b\/roll_flv2\.swf/i],[/flowplayer/i],[/manifest\.f4m/i],[/radikal\.ru\//i],[/jsonlock\.net\//i],
[/medbrowse\.com\.ua\/oops/i],[/\.yandex\./i],[/upload.*\/articles\//i],[/proxy\.com/i],[/ternopilmarket\.net\/modules\/goods\/images\//i],[/proxy.*\.media\.online\.ua\//i],[/\/picture.*_user\//i],[/img.*\.begun\.ru\//i],[/topdownloads\.ru\//i],[/gloker\.org\/upload/i],[/\/products_image\//i],[/gallery\.ru\//i],[/adxpansion\.com\//i],[/creoads\.com\//i],[/bm\.img\.com\.ua\//i],[/a\.s3\.ua\//i],[/servedbyadbutler\.com/i],[/kidstaff\.net/i],[/counter\.png/i],[100,100],[/\/image.*\/upload.*\//i],[/\/widget.*\//i],
[/lh.*\.ggpht\.com\//i],[/mathtag\.com/i],[/kavanga\.ru/i],[/anonymizer\.com\.ua/i],[/\.adnxs\.com/i],[/\.yadro\.ru/i],[/\/img.*\/photo.*\//i],[/\/foto\//i],[/odnoklassniki\./i],[/static\/images/i],[/\.vk\.me\//i],[/rollingstone\.com\//i],[/\/interview.*\//i],[/\/post.*\//i],[/ads.*\.contentabc\.com\//i],[/ads.*\.msn\.com\//i],[/ads\.webmasters\.ru\//i],[/ads\.vsisumy\.com\//i],[/ads\.trk4\.com\//i],[/ads\.trafficjunky\.net\//i],[/files\/images/i],[/ads\.porn.*\//i],[/4baby\.ua\/pictures/i],[/\.de\//i],
[/\/thumb.*\//i],[/ad\.drugasmuga\.com\/ban\.php/i],[/\/public\/images\/gallery\//i],[/imgn\.dt00\.net\//i],[/lcads\.ru\//i],[/img\.terrikon\.info\//i],[/\.ria\..*\/photos\//i],[/optimizedby\.brealtime\.com\//i],[/\/uploads\/posts/i],[/source\.mmi\.bemobile\.ua\/video\//i],[/avatar/i],[/\.pcads\.ru\//i],[78,78],[/uploads\.ru\//i],[88,40],[/fliphotos\.com\//i],[/rand_img\.php/i],[/\/images_slandocomua\//i],[/chrome-extension:/i],[/about:blank/i],[/data:/i],[/gazeta\.ua\/img\/preview\//i],[/www\.ex\.ua\/show\//i],
[/product.*picture/i],[/img\.gad\.org\.ua/i],[/1x1\.gif/i],[/vk\.jpg/i],[/c\.bigmir\.net/i],[/adlesse\.com/i],[/turzona\.com\.ua/i],[/kartinka\.com\.ua/i],[/totoro\.com\.ua/i],[/tas-ua\.toboads\.com/i],[/vk\.com/i],[/infrm\.weather\.ua\/image\//i],[/vk_banner/i],[/\.doubleclick\.net/i],[/googleads/i],[/twitter\.com/i],[/facebook\.com/i],[/captcha/i],[/images\.mob\.ua\//i],[/gorgeoushandbag\.com\//i],[/imgg\.dt0.*\.net\//i],[/banner\.ua\/cgi-bin\/core\.fcgi/i],[/adserve/i],[/adverserve\.net/i],[/yield.*\.com\//i],
[/serving.*\.com\//i],[/rmbn\.net\//i],[/tbn\.ru/i],[/adv\.fraza\.ua\//i],[/sinoptik\.ua\/_uploaded_files\/..\/..\/uft_................................\.jpg$/i],[/liga\.net\/www\/images\/.*\./i],[/x\.magnet\.kiev\.ua\/www\/images\/.*\./i],[/ads.*\.com\//i],/medtab\.com\.ua/,[/^http:\/\/medtab\.com\.ua\//i],/reitingi\.ge/,[/\/pictures\/image/i],/\.ge/,[/facebook\.com\//i],[/old\.amindi\.ge\/.*banner/i],/megogo\.net/,[/vcdn\.biz\/static\/.*\.jpg$/i],/hostinghost14\.com\//,[/^$/i],/timpul\.md/,[150,
60],/bona\.ua/,[/data\/small\//i],/kriminal\.tv/,[/image/i],/krisha\.kz/,[/\/i\/pro\//i],[120,90],[60,50],[70,50],/\.kz/,[/\/i\/0.*\.gif/i],/kolesa\.kz/,[60,50],[/\/idrive\//i],[/\/uploads\/content\//i],/magnolia-tv\.com/,[/pictures\/avatar\//i],/sport\.ua/,[/sport\.ua\/images\//i],/autocentre\.ua/,[/autocentre\.ua\/images\//i],/terrikon\.com/,[/\/fans\//i],/kievskaya\.com\.ua/,[/image\.tsn\.ua\//i],/mbox2\.i\.ua/,[/fsimg\.ru\//i],/uaua\.info/,[/\/pictures\//i],/telekritika\.ua/,[/telekritika\.ua.*\/imgs\//i],
[/telekritika\.ua.*\/images\//i],/meteo\.ua/,[/meteo\.ua\/var\/banners\/favorites_ua\.jpg/i],/smartphone\.ua/,[/smartphone\.ua\/img\//i],[240,400],/infohome\.com\.ua/,[250,250],/itc\.ua/,[/itc\.ua\/files\/pic/i],/hotline\.ua/,[/\/img\/tx\//i],[120,60],[120,60],/lissod\.com\.ua/,[/\/st_img\/flash\//i],/onlinetb\.com\.ua/,[200,200],[200,200],/delo\.ua/,[/inf\.korrespondent\.net/i],[/informers\.ukr\.net/i],[/inf\.korrespondent\.net/i],[/informers\.ukr\.net/i],/sport-express\.ua/,[/sport-express\.ua\/img\//i],
[/sport-express\.ua\/img\//i],/calend\.ru/,[/promo\.1000zakazov\.ru\//i],[/shkolazhizni\.ru\/img\/adv\//i],[/promo\.1000zakazov\.ru\//i],[/shkolazhizni\.ru\/img\/adv\//i],/bestdroid\.ru/,[/upload/i],[/upload/i],/hnb\.com\.ua/,[/artimage/i],[/artimage/i],/biathlon\.com\.ua/,[/img\/ministerstvo\.gif/i],[/img\/ministerstvo\.gif/i],/gazeta\.ua/,[300,240],[300,240],/mamaclub\.ua/,[300,250],/myradio\.ua/,[300,250],/oceni\.ua/,[250,250],/ava\.ua/,[240,400],/games\.bigmir\.net/,[/ads\..*\./i],/connect\.ua/,
[300,240],/bilshe\.com/,[/banner/i],/realty\.mail\.ru/,[/img\.pre\.realty\.mail\.ru\/.*\.jpg$/i],/pogoda\.mail\.ru/,[/r.*\.mail\.ru\/b.*\.jpg$/i],/cards\.mail\.ru/,[/r.*\.mail\.ru\/b.*\.png$/i],/hi-tech\.mail\.ru/,[/r.*\.mail\.ru\/b.*\.png$/i],[/r.*\.mail\.ru\/b.*\.jpg$/i],/otvet\.mail\.ru/,[/r.*\.mail\.ru\/b.*\.gif$/i],/health\.mail\.ru/,[/r.*\.mail\.ru\/b.*\.gif$/i],[/r.*\.mail\.ru\/b.*\.jpg$/i],/deti\.mail\.ru/,[/r.*\.mail\.ru\/b.*\.jpg$/i],/auto\.mail\.ru/,[/r.*\.mail\.ru\/b.*\.jpg$/i],/mail\.ru/,
[/ban\./i],[/\/adv\//i]]))},4);c.oa=function(f,g){r.B=c.o(d.c("templates:yes",f));r.N=c.o(d.c("templates:no",g))};return c}(C,I);(function(q,d,c,r,l,n){var s=(q=(q=f.performance)?q.timing:null)?new Date(q.navigationStart||q.connectStart):new Date,y=navigator.userAgent,z=/android|mobi|mini|blackberry|samsung|bada|nokia|series|symb(ian|os)|playstation/i.test(y),t=!(top===self||top===f),B=location.href.replace(location.hash,"");f.__cm||(q=f.__cm=[],c.extend(q,{on:r.on}));if(-1==c.indexOf(f.__cm,c.r())){tnscm_adn=
tnscm_adn||[];0>c.indexOf(tnscm_adn,"inline_cm")&&c.$(g,function(d){if(8===d.nodeType&&"MMI CMeter"===c.trim(d.nodeValue))return!0})&&tnscm_adn.push("inline_cm");var p=new l("video",{e:[],n:[],A:[],H:0,t:function(){var m=/MSIE/.test(y),g=/iPhone OS 3/.test(y);if(!t||d.work_in_frame)this.url=location.protocol+"//"+d.video.url,this.D=f.opera||m||g?"GET":"POST",setInterval(function(){p.g()},1E3*d.ads.scan_frequency),c.F(this.k,this.m),p.g()},k:function(){this.H=1},m:function(){this.H=0},append:function(d){if(-1==
c.indexOf(p.n,d)){var f=p.n.push(d);p.L(d,f-1);p.X(d)}},g:function(){c.a(g.getElementsByTagName("video"),p.append)},aa:function(c,d){for(;(c=c.parentElement)&&!c.classList.contains(d););return c},L:function(c,g){var a=c.currentSrc&&"data:video"==c.currentSrc.substring(0,10),b=c.currentSrc&&"blob:http"==c.currentSrc.substring(0,9);if(b&&/facebook.com\//.test(c.currentSrc)){var e=this.aa(c,"fbUserStory"),h=!1;e&&!e.querySelector(".timestampContent")&&(h=!0);if(h)for(var k=e.querySelector('input[name="ft_ent_identifier"]'),
k=k&&k.getAttribute("value"),e=e.querySelectorAll(".uiContextualLayerParent a"),h=e.length,l=0;l<h;l++){var n=e[l];if(n=n&&n.getAttribute("href").match(/www\.facebook\.com\/(.*)\//gi)){var q=n[0]+"videos/"+k;break}}}p.A[g]={duration:c.duration,width:c.clientWidth,height:c.clientHeight,src:a?d.juke_host[0]:b?f.location.href:c.currentSrc,id:p.V()+"."+g};k&&(p.A[g].src=q,p.A[g].ta=!0)},X:function(d){function f(a){var c="was"+a;"undefined"==typeof e[c]&&p.e[b].push(a);e[c]=!0}function a(a){e.d=0;e.q=
0;p.e[b]=a||[]}var b=c.indexOf(p.n,d),e=p.n[b],g;p.e[b]=p.e[b]||[];c.a(["canplay","play","timeupdate","pause"],function(e){c.on(d,e,function(e){"canplay"==e.type&&(f("READY"),a(["READY"]));"play"==e.type&&f("PLAY");"pause"==e.type&&a();"timeupdate"==e.type&&-1==c.indexOf(p.e[b],"ONLINE")&&p.e[b].push("ONLINE")})});a();3<e.readyState&&f("READY");g=setInterval(function(){null===e.parentNode?clearInterval(g):p.na(b)},1E3)},na:function(d){var f=new Date,a={},b=p.n[d];b.q+=1;b.q>=b.d&&!(1>p.e[d].length)&&
(-1<c.indexOf(p.e[d],"ONLINE")&&(a.currentTimer=b.d,10<=b.d&&(b.d+=5),10>b.d&&(b.d+=1),60<b.d&&(b.d=60),b.q=0),a.events=p.e[d],p.L(b,d),c.extend(a,p.A[d]),a.tabStatus=p.H,p.b.result=encodeURIComponent("["+JSON.stringify(a)+"]"),b.va=f,p.send(),p.e[d]=[])}}),x=new l("banners",{u:[],U:0,ja:1,T:[],t:function(){var g=/MSIE/.test(y),l=/iPhone OS 3/.test(y);if(!t||d.work_in_frame)this.D=f.opera||g||l?"GET":"POST",setInterval(function(){x.g(x.O)},1E3*d.ads.scan_frequency),this.b.sr=1,c.F(this.k,this.m),
x.g(x.O)},G:function(){this.referrer=B;this.U=0;this.u=[];this.ja++},k:function(){t?this.b.sr=2:delete this.b.sr},m:function(){this.b.sr=1},g:function(m){function l(a,b){function e(a){var b,c="",d="div[class*=brending];a[class*=branding];div[id*=branding] > a;div[class*=branding] > a;a[id*=branding];a".split(";"),f=d.length;if("A"==a.tagName)return a.getAttribute("href");for(a==g.body&&(c="body >");f--;)if(b=a.querySelectorAll(c+d[f]),!(3<b.length)&&b[0])return b[0].getAttribute("href")}function d(a){var b=
((a.currentStyle||f.getComputedStyle(a,null)||{}).backgroundImage||"").match(p);b&&b[1]&&300<=a.offsetWidth&&240<=a.offsetHeight&&(b=b[1].split('"').join(""),b!=f.location.href.split("#")[0]&&m.push({node:a,bg:b,cl:e(a)}))}var h=a.childNodes||[],k=h.length,m=l.items||[],n=["head","script","style"],r;if(0>=b)q&&(r=g.getElementById("branding_wrap")||g.getElementById("html-id"))&&(q=!1,l(r,4));else{for(l.items=m;k--;)1==h[k].nodeType&&0>c.indexOf(n,h[k].tagName.toLowerCase())&&(d(h[k]),l(h[k],b-1));
return l.items}}function a(b){function e(a){var b=c.J(a),f=c.K(a);f.w<=d.ads.width||f.h<=d.ads.height||!b||(a.I=b,h.push(a),k.push([b,f.w,f.h]))}function g(a){return a.addonCMeter&&a.addonCMeter.PLID?!0:!1}c.a(b.images||b.getElementsByTagName("img"),e);c.a(b.getElementsByTagName("svg"),e);c.a(n.embeds(b),e);c.a(b.getElementsByTagName("iframe"),function(b){var d,h=!1;c.ia(b)?(d=b.contentWindow||b.contentDocument.parent,d.__cm&&-1!=c.indexOf(d.__cm,c.r())||g(d)||(c.a(d.document.getElementsByTagName("script"),
function(a){a=c.J(a);/source\.mmi\.bemobile\.ua\/cm\/(cmeter_an|cm)\.js/.test(a)&&(h=!0)}),h||a(c.da(b)))):g(f)||e(b)})}var b=[],e=x.g.Y=x.g.Y||[],h=[],k=[],p=/\s*url\(\s*([^\)]+)\s*\)\s*/i,q=!0;-1===c.indexOf(e,m)&&e.push(m);a(g);for(c.a(n.g(k),function(a){b.push(h[a])});e.length;)e.shift()(b,l(g,4))},O:function(d,f){function a(){k=r.c("addDisappearBanner",k);k=r.c("banners",k);g.b.result=encodeURIComponent("["+k.join(",")+"]");k.length&&g.send()}function b(a,b,c,e){var d="",d='{"link":"'+a;b&&(d+=
'", "pos":"'+b);c&&(d+='", "cl":"'+c);e!=E&&(d+='", "bt":"'+e);return d+'"}'}function e(a){return-1==g.T.indexOf(a)?(g.T.push(a),!0):!1}var g=this,k=[],l={};c.a(f,function(c){var d,f=c.bg;if(e(f)){if("data:image/"==f.substr(0,11).toLowerCase()){if(l.hasOwnProperty(f))return;d=new Image;d.src=f;if(33>d.width&&33>d.height){l[f]=d;return}}k.push(b(f,0,c.cl,2));50<=k.length&&(a(),k=[])}});c.a(d,function(d){if(e(d.I)){var f=d.I,m=c.ca(d),l;if(c.la(d))l=c.K(d),d=c.fa(d).top+c.ea(l)+l.h;else{if(-1===c.indexOf(g.u,
d)){g.u.push(d);return}d=-1}k.push(b(f,d,m));50<=k.length&&(a(),k=[])}});a()}}),A=new l("timer",{t:function(){this.l=null;if(!t||d.work_in_frame&&!d.addon_disable_frame_timers)this.R=[],c.extend(this.R,d.timer.pings),c.load(this.Q),c.v(this.v),c.F(A.k,A.m)},ka:function(){try{return f.top.__cm?(clearInterval(this.interval),!1):!0}catch(c){return!0}},P:function(){var c=new Date,d=c-s;this.b[1]=Math.round(((this.s||c)-(this.C||s))/1E3);this.b[2]=this.l;this.b[4]=Math.round(d/1E3);if(!t||this.ka())this.p(),
this.p.time=c},W:function(){var c=new Date,f=Math.round((c-this.C)/1E3),c=Math.round((c-(this.p.time||0))/1E3)>=d.timer.frequency;this.C&&c&&(f>=60*d.timer.stop_after&&clearInterval(this.interval),f>=d.timer.pings[0]?(this.send(),1===d.timer.pings.length&&(this.ma=d.timer.pings[0]-this.M),this.M=d.timer.pings.shift()):0==f%this.ma?(this.send(),this.M=f):this.b[2]!==this.l&&this.send())},Q:function(c){this.b[3]=c-s;this.v()},k:function(){var c=new Date;if(!this.s)if(this.C=c,z){var f=this;setTimeout(function(){x.U+
x.u.length||f.W()},1E3*d.ads.scan_frequency+1E3)}else this.interval=setInterval(this.W,1E3),this.send()},m:function(){var c=new Date;this.s||(this.s=c,z||this.send(),clearInterval(this.interval))},v:function(){var d=g.body,f=g.documentElement,a=c.ga(),b="clientHeight"in f?f.clientHeight:0;d&&(b="CSS1Compat"===g.compatMode?f.clientHeight:d.clientHeight);a+b>=this.l&&(this.l=a+b)},G:function(){this.l=null;this.s=E;this.referrer=B;s=new Date;clearInterval(this.interval);if(!t||d.work_in_frame&&!d.addon_disable_frame_timers)c.load(this.Q),
this.b[3]=0,d.timer.pings=[],c.extend(d.timer.pings,this.R),this.k()}});setInterval(function(){var c=location.href.replace(location.hash,"");B!==c&&(x.G(),A.G(),B=c)},1E3*d.timer.check_location_timer||1E3);f.__cm.push(c.r())}})(L,F,C,I,O,M)})()})(window,document);